version: "3.8"

services:
  php-apache:
    build:
      context: .
      dockerfile: php-apache/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_USER_ID: ${PHP_USER_ID}
        PHP_USER_NAME: ${PHP_USER_NAME}
        PHP_GROUP_ID: ${PHP_GROUP_ID}
        PHP_GROUP_NAME: ${PHP_GROUP_NAME}
        PHP_DIR_PATH: ${PHP_DIR_PATH}
        PHP_APP_PORT: ${PHP_APP_PORT}
        PHP_MOUNT1: ${PHP_MOUNT1}
        PHP_MOUNT2: ${PHP_MOUNT2}
        PHP_SHELL: ${PHP_SHELL}
        PHP_HOSTNAME: ${PHP_HOSTNAME}
        PHP_ENV: ${PHP_ENV}
        PHP_HEALTH_URL: ${PHP_HEALTH_URL}
        PHP_VAR_RUN_PATH: ${PHP_VAR_RUN_PATH}
        PHP_CP_SRC: ${PHP_CP_SRC}
        PHP_CP_PHP_CFG: ${PHP_CP_PHP_CFG}
        PHP_CP_APACHE_CFG: ${PHP_CP_APACHE_CFG}
        PHP_VAR_LOGS: ${PHP_VAR_LOGS}
        TZ: ${TZ}
    container_name: my_php_apache
    hostname: ${PHP_HOSTNAME}
    environment:
      USER_NAME: ${PHP_USER_NAME}
      USER_ID: ${PHP_USER_ID}
      GROUP_ID: ${PHP_GROUP_ID}
      GROUP_NAME: ${PHP_GROUP_NAME}
      DIR_PATH: ${PHP_DIR_PATH}
      APP_PORT: ${PHP_APP_PORT}
      MOUNT1_PATH: ${PHP_MOUNT1}
      MOUNT2_PATH: ${PHP_MOUNT2}
      SHELL_PATH: ${PHP_SHELL}
      HOSTNAME: ${PHP_HOSTNAME}
      HEALTH_URL: ${PHP_HEALTH_URL}
      APP_ENV: ${PHP_ENV}
      VAR_RUN: ${PHP_VAR_RUN_PATH}
      VAR_LOGS: ${PHP_VAR_LOGS}
      CP_SRC: ${PHP_CP_SRC}
      CP_PHP_CFG: ${PHP_CP_PHP_CFG}
      TZ: ${TZ}
    depends_on:
      - mysql-db
    networks:
      - web-app-net
    dns:
      - ${DNS_PRIMARY}
      - ${DNS_SECONDARY}
    ports:
      - "${PHP_EXTERNAL_PORT}:${PHP_APP_PORT}"
    volumes:
      - php_data:${PHP_MOUNT1}
      - php_logs:${PHP_MOUNT2}
      - ./php-apache/src:/var/www/html/
    deploy:
      resources:
        limits:
          memory: ${PHP_MEMORY_LIMIT}
          cpus: ${PHP_CPU_LIMIT}
        reservations:
          memory: ${PHP_MEMORY_RESERVATION}
          cpus: ${PHP_CPU_RESERVATION}
    ulimits:
      nofile:
        soft: ${ULIMIT_NOFILE_SOFT}
        hard: ${ULIMIT_NOFILE_HARD}
      nproc:
        soft: ${ULIMIT_NPROC_SOFT}
        hard: ${ULIMIT_NPROC_HARD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f ${PHP_HEALTH_URL} || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILES}
        compress: ${LOG_COMPRESS}
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
    user: "${PHP_USER_ID}:${PHP_GROUP_ID}"
    restart: unless-stopped
    working_dir: /var/www/html/

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - mysql-db
    ports:
      - "${ADMINER_EXTERNAL_PORT}:8080"
    networks:
      - web-app-net
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
      TZ: ${TZ}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILES}
        compress: ${LOG_COMPRESS}

  mysql-db:
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_USER_ID: ${MYSQL_USER_ID}
        MYSQL_USER_NAME: ${MYSQL_USER_NAME}
        MYSQL_GROUP_ID: ${MYSQL_GROUP_ID}
        MYSQL_GROUP_NAME: ${MYSQL_GROUP_NAME}
        MYSQL_APP_PORT: ${MYSQL_APP_PORT}
        MYSQL_APP_ENV: ${MYSQL_APP_ENV}
        MYSQL_BASH_SHELL: ${MYSQL_BASH_SHELL}
        MYSQL_APP_DIR: ${MYSQL_APP_DIR}
        MYSQL_MOUNT1: ${MYSQL_MOUNT1}
        MYSQL_MOUNT2: ${MYSQL_MOUNT2}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        TZ: ${TZ}
        MYSQL_CHARSET: ${MYSQL_CHARSET}
        MYSQL_COLLATION: ${MYSQL_COLLATION}
        MYSQL_LOWER_CASE_TABLE_NAMES: ${MYSQL_LOWER_CASE_TABLE_NAMES}
        MYSQL_MAX_CONNECTIONS: ${MYSQL_MAX_CONNECTIONS}
        MYSQL_INNODB_BUFFER_POOL_SIZE: ${MYSQL_INNODB_BUFFER_POOL_SIZE}
    container_name: mysql-db
    hostname: mysql-host
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SQLVER: ${MYSQL_VERSION}
      USER_ID: ${MYSQL_USER_ID}
      USER_NAME: ${MYSQL_USER_NAME}
      GROUP_ID: ${MYSQL_GROUP_ID}
      GROUP_NAME: ${MYSQL_GROUP_NAME}
      APP_PORT: ${MYSQL_APP_PORT}
      APP_ENV: ${MYSQL_APP_ENV}
      BASH_SHELL: ${MYSQL_BASH_SHELL}
      APP_DIR: ${MYSQL_APP_DIR}
      MOUNT1: ${MYSQL_MOUNT1}
      MOUNT2: ${MYSQL_MOUNT2}
      TZ: ${TZ}
      MYSQL_CHARSET: ${MYSQL_CHARSET}
      MYSQL_COLLATION: ${MYSQL_COLLATION}
      MYSQL_LOWER_CASE_TABLE_NAMES: ${MYSQL_LOWER_CASE_TABLE_NAMES}
      MYSQL_MAX_CONNECTIONS: ${MYSQL_MAX_CONNECTIONS}
      MYSQL_INNODB_BUFFER_POOL_SIZE: ${MYSQL_INNODB_BUFFER_POOL_SIZE}
    networks:
      - web-app-net
    dns:
      - ${DNS_PRIMARY}
      - ${DNS_SECONDARY}
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_APP_PORT}"
    volumes:
      - mysql_data:${MYSQL_MOUNT1}
      - mysql_logs:${MYSQL_MOUNT2}
    deploy:
      resources:
        limits:
          memory: ${MYSQL_MEMORY_LIMIT}
          cpus: ${MYSQL_CPU_LIMIT}
        reservations:
          memory: ${MYSQL_MEMORY_RESERVATION}
          cpus: ${MYSQL_CPU_RESERVATION}
    ulimits:
      nofile:
        soft: ${ULIMIT_NOFILE_SOFT}
        hard: ${ULIMIT_NOFILE_HARD}
      nproc:
        soft: ${ULIMIT_NPROC_SOFT}
        hard: ${ULIMIT_NPROC_HARD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysqladmin ping -h localhost -u root --password="${MYSQL_ROOT_PASSWORD}" || (echo ''Health check failed'' >> /sqldb/logs/mysql_health.log && exit 1)',
        ]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILES}
        compress: ${LOG_COMPRESS}
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - SYS_RESOURCE
    user: "${MYSQL_USER_ID}:${MYSQL_GROUP_ID}"
    restart: unless-stopped
    working_dir: ${MYSQL_APP_DIR}

volumes:
  php_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PHP_DATA_PATH}
  php_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PHP_LOGS_PATH}
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MYSQL_DATA_PATH}
  mysql_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MYSQL_LOGS_PATH}

networks:
  web-app-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
