version: "3.8"

services:
  php-apache:
    build:
      context: .
      dockerfile: php-apache/Dockerfile
      args:
        PHPVER: 8.1-apache
        USER_ID: 1100
        USER_NAME: phpapacheuser
        GROUP_ID: 1100
        GROUP_NAME: phpapachegrp
        DIR_PATH: /var/www/html/
        APP_PORT: 8989
        MOUNT1: /php/data
        MOUNT2: /php/logs
        SHELL: /bin/bash
        hostname: php-apache-host
        PHP_ENV: production
        HEALTH_URL: "curl -f http://localhost:8989"
        VAR_RUN_PATH: /var/run/apache2
        CP_PHP_SRC: /php-apache/src
        CP_PHP_CFG: /php-apache/php-config
        CP_APACHE_CFG: /php-apache/apache-config
        VAR_LOGS: /var/log/apache2

    container_name: my_php_apache
    hostname: php-apache-host
    labels:
      - "maintainer=farajassulai"
      - "app=php-apache-app"
      - "service=phpapache"
      - "tier=application"
      - "environment=production"
      - "maintainer=farajassulai@gmail.com"
      - "description=php-apache2 application with custom configuration"
      - "date-created=2025-06-20"
      - "version=8.1-apache"
    environment:
      USER_NAME: phpapacheuser
      USER_ID: 1100
      GROUP_NAME: phpapachegrp
      DIR_PATH: /var/www/html/
      APP_PORT: 8989
      MOUNT1_PATH: /php/data
      MOUNT2_PATH: /php/logs
      SHELL_PATH: /bin/bash
      HOSTNAME: php-apache-host
      HEALTH_URL: "curl -f http://localhost:8989"
      VAR_RUN: /var/run/apache2
      VAR_LOGS: /var/log/apache2
      TZ: Europe/Paris
    depends_on:
      - mysql-db
    networks:
      - web-app-net
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "8989:8989"
    volumes:
      - php_data:/php/data
      - php_logs:/php/logs
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.5'
        reservations:
          memory: 512m
          cpus: '0.25'
    ulimits:
      nofile:
        soft: 1024
        hard: 65536
      nproc:
        soft: 1024
        hard: 4096
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8989/health || exit 1"
        ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
        compress: "true"
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
    user: "1100:1100"
    restart: unless-stopped
    working_dir: /var/www/html/

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - mysql-db
    ports:
      - "8181:8181"
    networks:
      - web-app-net
    restart: unless-stopped

  mysql-db:
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        SQLVER: 8.0
        USER_ID: 1010
        USER_NAME: sqluser
        GROUP_ID: 1010
        GROUP_NAME: sqlgroup
        APP_PORT: 3306
        APP_ENV: production
        BASH_SHELL: /bin/bash
        APP_DIR: /sqldb
        MOUNT1: /sqldb/data
        MOUNT2: /sqldb/logs
        MYSQL_ROOT_PASSWORD: ${{MYSQL_ROOT_PASSWORD}}
        MYSQL_DATABASE: ${{MYSQL_DATABASE}}
        MYSQL_USER: ${{MYSQL_USER}}
        MYSQL_PASSWORD: ${{MYSQL_PASSWORD}}

    container_name: mysql-project
    hostname: mysql-host
    labels:
      - "maintainer=farajassulai"
      - "app=mysql-database"
      - "service=database"
      - "tier=database"
    environment:
      MYSQL_ROOT_PASSWORD: ${{MYSQL_ROOT_PASSWORD}}
      MYSQL_DATABASE: ${{MYSQL_DATABASE}}
      MYSQL_USER: ${{MYSQL_USER}}
      MYSQL_PASSWORD: ${{MYSQL_PASSWORD}}
      TZ: Europe/Paris
    networks:
      - web-app-net
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/sqldb/data
      - mysql_logs:/sqldb/logs
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.5'
        reservations:
          memory: 512m
          cpus: '0.25'
    ulimits:
      nofile:
        soft: 1024
        hard: 65536
      nproc:
        soft: 1024
        hard: 4096
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root --password=\"${{MYSQL_ROOT_PASSWORD}}\" || exit 1"
        ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
        compress: "true"
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - SYS_RESOURCE
    user: "1010:1010"
    restart: unless-stopped
    working_dir: /sqldb

volumes:
  php_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/php_data
  php_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/php_logs
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/mysql_data
  mysql_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/mysql_logs

networks:
  web-app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.19.0/24