```yaml
version: "3.8"

services:
  nginx-lb:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-app-net
    restart: unless-stopped

networks:
  web-app-net:
    external: true
```
